services:
  # MongoDB 服务配置
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "127.0.0.1:${MONGO_PORT}:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - mongodb_network
    command: ["--bind_ip_all"]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "50m"     # 单个日志文件最大SIZE，按需调整
        max-file: "10"      # 最多保留的日志文件数，按需调整
    deploy:
      resources:
        limits:
          cpus: '4'         # 4个核心，按需调整
          memory: 4G        # 4GB内存，按需调整
        reservations:
          cpus: '2'         # 2个核心，按需调整
          memory: 4G        # 4GB内存，按需调整

  # MongoDB Express Web 界面
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "127.0.0.1:${MONGO_EXPRESS_PORT}:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
    depends_on:
      - mongodb
    networks:
      - mongodb_network
    logging:
      driver: "json-file"
      options:
        max-size: "20m"     # 单个日志文件最大SIZE，按需调整
        max-file: "5"       # 最多保留的日志文件数，按需调整
    deploy:
      resources:
        limits:
          cpus: '1'         # 1个CPU核心，按需调整
          memory: 512M      # 512MB内存，按需调整
        reservations:
          cpus: '0.5'       # 0.5个CPU核心，按需调整
          memory: 256M      # 256MB内存，按需调整

networks:
  mongodb_network:
    driver: bridge

volumes:
  mongodb_data:
  mongodb_config: